# Generated by Django 2.0.6 on 2018-06-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0002_readdetal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadDetal',
            new_name='ReadDetail',
        ),
    ]
