# Generated by Django 2.0.6 on 2018-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='abstract',
            field=models.CharField(blank=True, max_length=54, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='please write a title', max_length=70, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='topped',
            field=models.BooleanField(default=False, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
