# Generated by Django 2.0.6 on 2018-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20180609_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='abstract',
            field=models.CharField(blank=True, max_length=54, verbose_name='abstract'),
        ),
    ]
