# Generated by Django 2.0.6 on 2018-06-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20180609_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topped',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='views',
        ),
    ]
