# Generated by Django 2.0.6 on 2018-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_remove_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='excerpt',
            field=models.CharField(blank=True, max_length=54),
        ),
    ]
