# Generated by Django 2.0.6 on 2018-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_entry_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('y', '原创'), ('z', '转载')], default='y', max_length=10),
        ),
    ]
