# Generated by Django 2.0.6 on 2018-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0013_auto_20180609_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('y', '原创'), ('z', '转载')], default='y', max_length=10, verbose_name='文章分类'),
        ),
    ]
