# Generated by Django 2.0.6 on 2018-06-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0018_auto_20180611_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='name',
        ),
    ]
