# Generated by Django 2.0.6 on 2018-06-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0019_auto_20180611_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic', verbose_name='博客分类'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
