# Generated by Django 2.0.6 on 2018-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0020_auto_20180611_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='abstract',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
