# Generated by Django 2.0.6 on 2018-06-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0025_remove_entry_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
