# Generated by Django 2.0.6 on 2018-06-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0026_entry_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='views',
        ),
    ]
