# Generated by Django 2.0.6 on 2018-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0027_remove_entry_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='views',
        ),
        migrations.AddField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
