# Generated by Django 2.0.6 on 2018-06-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0028_auto_20180616_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='entry',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
