# Generated by Django 2.0.6 on 2018-06-25 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0030_auto_20180617_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='abstract',
            field=models.TextField(help_text='简单概括一下这个主题', max_length=200, verbose_name='主题简介'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='主题名称'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
